service: thumbnail-resize
app: thumbnail-resize
org: archermcneill

provider:
  name: aws
  runtime: nodejs10.x

  # you can overwrite defaults here
  stage: dev
  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

plugins:
  - serverless-webpack

# you can add packaging information here
package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    
  s3Prefix: ${self:service.name}-${self:provider.stage}-s3
  lambdaPrefix: ${self:service.name}-${self:provider.stage}-lambda

functions:
  upload:
    name: ${self:custom.lambdaPrefix}-upload
    handler: handlers/upload.handler
    events:
      - http:
          path: images/upload
          method: post

  resize:
    name: ${self:custom.lambdaPrefix}-resize
    handler: handlers/resize.handler
    events:
      - s3:
          bucket: ${self:custom.s3Prefix}-images
          event: s3:ObjectCreated:*

# you can add CloudFormation resource templates here
resources:
  Resources:
    ThumbnailBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3Prefix}-thumbnails
